# Generated by Django 3.0.3 on 2020-04-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_auto_20200429_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
