# Generated by Django 3.0.3 on 2020-04-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_auto_20200429_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pk', '-publish_date', '-updated', '-timestamp']},
        ),
    ]
