# Generated by Django 3.0.3 on 2020-04-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_auto_20200429_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
