# Generated by Django 3.0.3 on 2020-05-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0013_auto_20200502_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='height_field',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='width_field',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='Post_pic.jpg', height_field='height_field', upload_to='Blog_image', width_field='width_field'),
        ),
    ]
