# Generated by Django 3.0.3 on 2020-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0017_auto_20200528_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostlike',
            old_name='user',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='follow',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('M', 'Music'), ('C', 'Comedy'), ('L', 'Lifestyle'), ('E', 'Education')], default=1, max_length=3),
        ),
    ]
