# Generated by Django 3.0.3 on 2020-05-28 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coding', '0018_auto_20200528_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostUnlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.BlogPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='blogpostlike',
            old_name='post',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='BlogPostFollow',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='unlike',
            field=models.ManyToManyField(blank=True, related_name='post_unlike', through='coding.BlogPostUnlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
